name: CI check

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  go-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: golangci-lint-check
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: backend
          golangci_lint_version: v2.11.3
          golangci_lint_flags: "-c .golangci.yaml ./..."
          reporter: github-pr-review
          fail_level: error

  go-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Run tests
        run: make test

  go-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3
      - name: Check format
        run: |
          make fmt
          git diff --exit-code

  go-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Build
        run: make build

  go-mod-tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Check go mod tidy
        run: |
          make tidy
          git diff --exit-code go.mod go.sum
