name: CI check

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  go-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.3
          working-directory: backend
          args: -c .golangci.yaml ./...
      - name: Check format
        working-directory: backend
        run: |
          golangci-lint fmt
          git diff --exit-code

  go-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Run tests
        run: make test

  go-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Build
        run: make build

  go-mod-tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum
      - name: Check go mod tidy
        run: |
          make tidy
          git diff --exit-code go.mod go.sum
